### ISSUE TITLE
Compiling in platformio

### ISSUE THREAD

**Issue by snowkingcro** [p-h-a-i-l/hoverboard-firmware-hack#10]
Hello, thanks for your effort and help with my issue in Niklas's repo.
So, i finally got some time to work on my project again, and i used your repo because it seems easier to compile.
QUESTION: 
you said that i would need some editing within platformio... you ment to change the file for the output, so i would get a .hex file in the end?
i got this, so i changed the input for my PPM decoder, so i would like to confirm that this is the file that i need to flash my hoverboard!
![Untitled](https://user-images.githubusercontent.com/46979217/59869154-f23b6d80-9392-11e9-98ea-cb03405cd082.png)

**Comment by p-h-a-i-l** [comment]
Hi, you're welcome!
I'm not really sure, if that is the file you're looking for, but .pioenvs does look like the correct location! (I do upload from vscode directly, just one button press.

Regarding platformio.ini.. if you have a look at that file, you can see that 3 environments are defined. The first one (which I can see you were using in your screenshots) takes all config parameters from config.h. For my convenience I created some more environments which override the config.h settings. This way I can have multiple sets of settings for different applications without the need to always change config.h.

For a start you can just use  `env_default = genericSTM32F103RC` like you did and edit config.h.

BTW: I'm working on merging all my modifications to https://github.com/bipropellant/bipropellant-hoverboard-firmware . For now I'm still using this repo here because it is very stable, but as soon as the bugs in bipropellant are fixed, it will be far superior ;)

**Comment by snowkingcro** [comment]
Well this repo seems fine to me, as i am trying to use an arduino board to convert my Rc Car PWM signal to ADC signal to control the boards speed and steering, but i will try to recompile to test it for PPM decoder usage... But, if the new repo goes better, I'll give it a try... 😎😎
