### ISSUE TITLE
Bidirectional USART control

### ISSUE THREAD

**Issue by EFeru** [p-h-a-i-l/hoverboard-firmware-hack#13]
HI @p-h-a-i-l ,

I know this branch is not supported any more, but I didn't know how to contact you.

I try to implement bi-directional USART control on my FOC branch and I got stuck in something.
Whenever I try to send or receive on huart3, I can only do it once and then the STM32 get's stuck.
So if I do:
```
HAL_UART_Transmit_DMA(&huart3, (uint8_t *)message, strlen(message));
```
where message = "Hello";

Then on serial Monitor I see
Hello
after which the STM32 gets stuck in an infinite loop. I followed your settings from this branch for the bidirectional USAR control. Did I miss something? How did you manage to work?

If I compile this brach I get on Serial Monitor "power off in 4s" and then infinite beeping.

**Comment by p-h-a-i-l** [comment]
Hi @EmanuelFeru,
basically the UART setup here is the same as in bipropellant. But since this fork here is stale, I'd rather not warm up old code. Look at bipropellant how it is done there. I used interrupt based UART because it is easier to setup. Look for the SERIAL_USART3_IT keyword in the code to see what is done to setup and send.
(You can also contact me via telegram, I've already seen you writing there ;) )

**Comment by EFeru** [comment]
Aa thanks! I will do that! I will close the topic here.
I didn't know you were in Telegram :)
